credentials:
  usernames:
    Brian:
      email: brian.bassey@Azubiafrica.org
      logged_in: false
      name: Brian
      password: Password123
    Tirusew:
      email: tirusewcheru@gmail.com
      logged_in: false
      name: Tirusew
      password: Chat@2024
    brianbassey:
      email: ''
      logged_in: false
      name: brianbassey
      password: '123456789'
