import streamlit as st
import pandas as pd
import pyodbc
import os

# Load secrets
secrets = st.secrets["database"]

@st.cache(allow_output_mutation=True)
def connect_to_database():
    server = secrets['server']
    database = secrets['database']
    username = secrets['username']
    password = secrets['password']
    connection_string = f"DRIVER=SQL Server;SERVER={server};DATABASE={database};UID={username};PWD={password}"
    return pyodbc.connect(connection_string)

def list_tables():
    connection = connect_to_database()
    cursor = connection.cursor()
    query = "SELECT table_name FROM INFORMATION_SCHEMA.TABLES WHERE table_type = 'BASE TABLE';"
    cursor.execute(query)
    tables = cursor.fetchall()
    st.write("Tables in the database:")
    st.write([table[0] for table in tables])

def read_data(query):
    connection = connect_to_database()
    cursor = connection.cursor()
    cursor.execute(query)
    columns = [column[0] for column in cursor.description]
    data = cursor.fetchall()
    return pd.DataFrame.from_records(data, columns=columns)
